-- Exploratory Data Analysis


-- Exploring all objects in the database

SELECT 
	*
FROM INFORMATION_SCHEMA.TABLES

---------------------------------------------------------

-- Exploring all columns in the database

SELECT
	*
FROM INFORMATION_SCHEMA.Columns
WHERE TABLE_NAME = 'dim_customers';

---------------------------------------------------------

-- for dimensions columns, these are the columns which are either contain string or textual values or numbers that don't make sense when aggregating them like unique identifiers,
-- exploring these dimensions by slelecting the distinct categories or values to have a general overview 

SELECT DISTINCT country FROM gold.dim_customers;


SELECT DISTINCT category FROM gold.dim_products;


SELECT DISTINCT category, subcategory FROM gold.dim_products;


SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 3,2,1 ;


---------------------------------------------------------


-- Date Exploration: boundaries and the timespan

SELECT
	MIN(Order_date) first_order_date,
	MAX(Order_date) last_order_date,
	DATEDIFF(YEAR, MIN(Order_date), MAX(Order_date)) AS order_range_years,
	DATEDIFF(MONTH, MIN(Order_date), MAX(Order_date)) AS order_range_months
FROM gold.fact_sales


-- the youngest and oldest customers?

SELECT
	MIN(birthdate) AS oldest,
	MAX(birthdate) AS youngest
FROM gold.dim_customers;

---------------------------------------------------------

-- Measures Exploration
-- using aggregation functions we can explore the measures columns

-- for ex; total sales, number of orders, number of products, ... etc

-- total sales

SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales



-- how many items are sold?

SELECT SUM(quantity) AS total_quanitity FROM gold.fact_sales


-- the average selling price?

SELECT AVG(price) AS avg_price FROM gold.fact_sales



-- the total number of orders?

SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales


-- total number of products?

SELECT COUNT(product_key) AS total_products FROM gold.dim_products


-- total number of customers?

SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers



-- total number of customers taht has placed an order?

SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales


---------------------------------------------------------

-- then generating a report that shows all key metrics of the business discovered so far

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total_orders' AS measure_name, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total_products' AS measure_name, COUNT(product_key) AS measure_value  FROM gold.dim_products
UNION ALL
SELECT 'Total_Customers' AS measure_name, COUNT(customer_key) AS measure_value FROM gold.dim_customers
UNION ALL
SELECT 'Total_customers_orderd' AS measure_name, COUNT(DISTINCT customer_key) AS measure_value FROM gold.fact_sales



---------------------------------------------------------

-- Magnitude analysis: comparing mesures by categories to understand the importance of them
-- It's like aggregating the measures by dimensions


-- Here are some questions you might consider:

-- Total customers by country?

SELECT 
	country,
	COUNT(customer_key) AS 'Total_cusomers'
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_key) DESC;



-- Total Customers splited according to gender

SELECT
	gender,
	COUNT(customer_key) AS 'Total_customers'
FROM gold.dim_customers
GROUP BY gender;


-- Total products by category?

SELECT
	category,
	COUNT(product_key) AS 'Total Products'
FROM gold.dim_products
GROUP BY category;


-- Average costs in each category?

SELECT
	category,
	AVG(cost) AS 'Average Cost'
FROM gold.dim_products
GROUP BY category;

-- Total Revenue generated by each customer?
SELECT
	*
FROM gold.dim_customers

SELECT
	*
FROM gold.fact_sales


SELECT
	CONCAT(c.first_name, ' ', c.last_name) AS full_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_id = f.customer_key
GROUP BY CONCAT(c.first_name, ' ', c.last_name)
ORDER BY total_revenue DESC;


-- Total Revenue generated by each category?
SELECT
	*
FROM gold.dim_products

SELECT
	*
FROM gold.fact_sales


SELECT
	p.category,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- so we knew at a glance that our business is generating alot of money form the bikes category



-- Distribution of sold items across countries?

SELECT
	c.country,
	SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_id = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;




-- Low Cardinality Dimesnsion: Dimension with few unique values (e.g. category, country, and gender)
-- High Cardinality Dimension: Dimension with many unique values (e.g. product, customer, address)



---------------------------------------------------------

-- Ranking Analysis: ordering the values of dimesntions by measure to know to top N performers and bootom ones
-- Rank dimensions by measures (e.g. rank top 5 products by quantity)




-- which 5 products generated the higest revenue?

SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) total_revenue,
	ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS products_rank
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;


-- 5 worst performing items

SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC;


-- With that I've covered the EDA part of the project moving on to the reporting and advanced analytics part


---------------------------------------------------------------------------------------------------------------------------------------------------------------------------


-- Advanced Data Analytics and reporting
-- This could indlude analysis like: 1) change over time, 2) commulative analysis, 3) performance analytics, 4) part-to-whole analysis, 5) data segmentation and reporting and more



-- 1) change over time: analyzes how a measure evoloves over time. It helps track trends and identify seasonality in the data
--    for example: Aggregating a measure by a date dimension
--    usually in this kind of analysis we targer the fact table because it includes the sales and the date information


-- sales performance and number of customers over time?

SELECT
	YEAR(order_date) AS order_year,
	SUM(sales_amount) AS total_sales,
	COUNT(DISTINCT customer_key) AS total_customers
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY YEAR(order_date)
ORDER BY YEAR(order_date);


-- to analyze seasonality and more detailed analysis we could make it over month

SELECT
	YEAR(order_date) AS order_year,
	MONTH(order_date) AS order_month,
	SUM(sales_amount) AS total_sales,
	COUNT(DISTINCT customer_key) AS total_customers
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY YEAR(order_date), MONTH(order_date)
ORDER BY YEAR(order_date), MONTH(order_date);


---------------------------------------------------------



-- 2) Cumulative Analysis: Data Aggregation progressively over time. It helps to understand whether the business is growing or declining over time
--    for example, aggregating a cumulative measure by date dimensiton (e.g. running total or moving averages)



-- total sales per month and the running total of sales over time?


-- years running totals

SELECT
	order_date_year,
	total_sales,
	SUM(total_sales) OVER(ORDER BY order_date_year) AS running_total_sales
FROM(
		SELECT
			DATETRUNC(YEAR, order_date) AS order_date_year,
			SUM(sales_amount) AS total_sales
		FROM gold.fact_sales
		WHERE order_date IS NOT NULL
		GROUP BY DATETRUNC(YEAR, order_date)) t


-- months running totals

SELECT
	order_date_month,
	total_sales,
	SUM(total_sales) OVER(ORDER BY order_date_month) AS running_total_sales
FROM(
		SELECT
			DATETRUNC(MONTH, order_date) AS order_date_month,
			SUM(sales_amount) AS total_sales
		FROM gold.fact_sales
		WHERE order_date IS NOT NULL
		GROUP BY DATETRUNC(MONTH, order_date)) t


---------------------------------------------------------



-- 3) Performance Analysis: Comparing current values with target values
--    for example, current[measure] -  target[measure]


-- analyze the yearly performance of products by comparing each products sales to both its averate sales performance and the previous's years sales

WITH yearly_sales AS (
						SELECT
							YEAR(f.order_date) AS order_year,
							p.product_name,
							SUM(f.sales_amount) AS current_sales
						FROM gold.fact_sales f
						LEFT JOIN gold.dim_products p
						ON f.product_key = p.product_key
						WHERE f.order_date IS NOT NULL 
						GROUP BY YEAR(f.order_date), p.product_name)

SELECT 
	order_year,
	product_name,
	current_sales,
	AVG(current_sales) OVER(PARTITION BY product_name) avg_sales,
	current_sales - AVG(current_sales) OVER(PARTITION BY product_name) AS diff,
	CASE 
		WHEN current_sales - AVG(current_sales) OVER(PARTITION BY product_name) > 0 THEN 'Above Avg'
		WHEN current_sales - AVG(current_sales) OVER(PARTITION BY product_name) < 0 THEN 'Belos Avg'
		ELSE 'Exactly the Average' 
	END AS avg_change,
	LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_year) previous_year,
	current_sales - LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_year) AS diff_PYear,
	CASE 
		WHEN current_sales - LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_year) > 0 THEN 'Increase'
		WHEN current_sales - LAG(current_sales) OVER(PARTITION BY product_name ORDER BY order_year) < 0 THEN 'Decrease'
		ELSE 'No change' 
	END AS avg_change
FROM yearly_sales 
ORDER BY product_name, order_year



---------------------------------------------------------


-- 4) Part to whole analysis: analyzing how an idividual part is performing compared to the overall, allowing to understand which category has the greatest impact on the business
--    for ex, ( measure / total of that measure) * 100 grouped by certain dimension



-- which categories contribute the most to overall sales?



SELECT 
	category,
	Total_sales,
	SUM(Total_sales) OVER() AS overall_sales,
	CONCAT(ROUND((CAST(Total_sales AS FLOAT) / SUM(Total_sales) OVER() * 100), 2), '%') AS contribution
FROM (
		SELECT
		p.category,
		SUM(f.sales_amount) AS Total_sales
	FROM gold.fact_sales AS f
	LEFT JOIN gold.dim_products AS p
	ON p.product_key = f.product_key
	GROUP BY p.category ) AS t
 




 ---------------------------------------------------------


-- 4) Data Segmentation Analytics: Grouping the data based on specific range. Helps understand the correlation between two measures
--    for ex, correlation between two measures



-- segment the products into cost ranges

WITH product_segment AS (
SELECT
	product_key,
	product_name,
	cost,
	CASE	
		WHEN cost < 100 THEN 'below 100'
		WHEN cost BETWEEN 100 AND 1000 THEN '100-1000'
		ELSE 'Above 1000'
	END AS cost_range
FROM gold.dim_products) 

SELECT 
	cost_range,
	COUNT(product_key) AS total_products
FROM product_segment
GROUP BY cost_range
ORDER BY total_products DESC;



-- group customers into 3 segments based on their spending behavior and date

SELECT
	*
FROM gold.fact_sales



SELECT
	customer_segment,
	COUNT(customer_key) AS number_of_customers
FROM (
SELECT 
	customer_key,
	total_spending,
	lifespan,
	CASE	
		WHEN lifespan > 12 AND total_spending > 5000 THEN 'VIP'
		WHEN lifespan <= 12 AND total_spending < 5000 THEN 'Regular'
		ELSE 'New'
	END AS customer_segment
FROM (
	SELECT
		customer_key,
		SUM(sales_amount) AS total_spending,
		MIN(order_date) AS first_order,
		MAX(order_date) AS last_order,
		DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) lifespan
	FROM gold.fact_sales
	GROUP BY customer_key) t) l
GROUP BY customer_segment;



-----------------------------------------------------------------------------------------------------------------------------------------------------

/*
---------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------
Customer Report
---------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------
Purpose:
    This report consolidates key customer metrics and behaviors

Highlights:
	1. Gathers essential fields such as names, ages, and transaction details.
	2. Segments customers into categories (VIP, Regular, New) and age groups.

	3. Aggregates customer-level metrics:
		total orders
		total sales
		total quantity purchased
		total products
		lifespan (in months)

	4. Calculates valuable KPIs:
		recency (months since last order)
		average order value
		average monthly spend

================================================================================
*/




CREATE VIEW gold.report_customers AS

WITH base_query AS(
/*---------------------------------------------------------------------------
1) Base Query: Retrieves core columns from tables
---------------------------------------------------------------------------*/
SELECT
f.order_number,
f.product_key,
f.order_date,
f.sales_amount,
f.quantity,
c.customer_key,
c.customer_number,
CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
DATEDIFF(year, c.birthdate, GETDATE()) age
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
WHERE order_date IS NOT NULL)

, customer_aggregation AS (
/*---------------------------------------------------------------------------
2) Customer Aggregations: Summarizes key metrics at the customer level
---------------------------------------------------------------------------*/
SELECT 
	customer_key,
	customer_number,
	customer_name,
	age,
	COUNT(DISTINCT order_number) AS total_orders,
	SUM(sales_amount) AS total_sales,
	SUM(quantity) AS total_quantity,
	COUNT(DISTINCT product_key) AS total_products,
	MAX(order_date) AS last_order_date,
	DATEDIFF(month, MIN(order_date), MAX(order_date)) AS lifespan
FROM base_query
GROUP BY 
	customer_key,
	customer_number,
	customer_name,
	age
)
SELECT
customer_key,
customer_number,
customer_name,
age,
CASE 
	 WHEN age < 20 THEN 'Under 20'
	 WHEN age between 20 and 29 THEN '20-29'
	 WHEN age between 30 and 39 THEN '30-39'
	 WHEN age between 40 and 49 THEN '40-49'
	 ELSE '50 and above'
END AS age_group,
CASE 
    WHEN lifespan >= 12 AND total_sales > 5000 THEN 'VIP'
    WHEN lifespan >= 12 AND total_sales <= 5000 THEN 'Regular'
    ELSE 'New'
END AS customer_segment,
last_order_date,
DATEDIFF(month, last_order_date, GETDATE()) AS recency,
total_orders,
total_sales,
total_quantity,
total_products
lifespan,
-- Compuate average order value (AVO)
CASE WHEN total_sales = 0 THEN 0
	 ELSE total_sales / total_orders
END AS avg_order_value,
-- Compuate average monthly spend
CASE WHEN lifespan = 0 THEN total_sales
     ELSE total_sales / lifespan
END AS avg_monthly_spend
FROM customer_aggregation




 ----------------------------------------------------------------------------------------------------------

CREATE VIEW gold.report_products AS




/*
===============================================================================
Product Report
===============================================================================
Purpose:
    - This report consolidates key product metrics and behaviors.

Highlights:
    1. Gathers essential fields such as product name, category, subcategory, and cost.
    2. Segments products by revenue to identify High-Performers, Mid-Range, or Low-Performers.
    3. Aggregates product-level metrics:
       - total orders
       - total sales
       - total quantity sold
       - total customers (unique)
       - lifespan (in months)
    4. Calculates valuable KPIs:
       - recency (months since last sale)
       - average order revenue (AOR)
       - average monthly revenue
===============================================================================
*/
-- =============================================================================
-- Create Report: gold.report_products
-- =============================================================================
IF OBJECT_ID('gold.report_products', 'V') IS NOT NULL
    DROP VIEW gold.report_products;
GO

CREATE VIEW gold.report_products AS

WITH base_query AS (
/*---------------------------------------------------------------------------
1) Base Query: Retrieves core columns from fact_sales and dim_products
---------------------------------------------------------------------------*/
    SELECT
	    f.order_number,
        f.order_date,
		f.customer_key,
        f.sales_amount,
        f.quantity,
        p.product_key,
        p.product_name,
        p.category,
        p.subcategory,
        p.cost
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
        ON f.product_key = p.product_key
    WHERE order_date IS NOT NULL  -- only consider valid sales dates
),

product_aggregations AS (
/*---------------------------------------------------------------------------
2) Product Aggregations: Summarizes key metrics at the product level
---------------------------------------------------------------------------*/
SELECT
    product_key,
    product_name,
    category,
    subcategory,
    cost,
    DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS lifespan,
    MAX(order_date) AS last_sale_date,
    COUNT(DISTINCT order_number) AS total_orders,
	COUNT(DISTINCT customer_key) AS total_customers,
    SUM(sales_amount) AS total_sales,
    SUM(quantity) AS total_quantity,
	ROUND(AVG(CAST(sales_amount AS FLOAT) / NULLIF(quantity, 0)),1) AS avg_selling_price
FROM base_query

GROUP BY
    product_key,
    product_name,
    category,
    subcategory,
    cost
)

/*---------------------------------------------------------------------------
  3) Final Query: Combines all product results into one output
---------------------------------------------------------------------------*/
SELECT 
	product_key,
	product_name,
	category,
	subcategory,
	cost,
	last_sale_date,
	DATEDIFF(MONTH, last_sale_date, GETDATE()) AS recency_in_months,
	CASE
		WHEN total_sales > 50000 THEN 'High-Performer'
		WHEN total_sales >= 10000 THEN 'Mid-Range'
		ELSE 'Low-Performer'
	END AS product_segment,
	lifespan,
	total_orders,
	total_sales,
	total_quantity,
	total_customers,
	avg_selling_price,
	-- Average Order Revenue (AOR)
	CASE 
		WHEN total_orders = 0 THEN 0
		ELSE total_sales / total_orders
	END AS avg_order_revenue,

	-- Average Monthly Revenue
	CASE
		WHEN lifespan = 0 THEN total_sales
		ELSE total_sales / lifespan
	END AS avg_monthly_revenue

FROM product_aggregations 












